// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnd3W2yUHsH2FxqTGCY_afUGNU3oyTlpw',
    appId: '1:418708659686:web:7d33a23db5ded907c88a27',
    messagingSenderId: '418708659686',
    projectId: 'linquachat',
    authDomain: 'linquachat.firebaseapp.com',
    storageBucket: 'linquachat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2CSO6t9i6mBnmiEotBbAkS71qd_8LIkE',
    appId: '1:418708659686:android:e247109c45e8c202c88a27',
    messagingSenderId: '418708659686',
    projectId: 'linquachat',
    storageBucket: 'linquachat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ2GLveL72qrI9MAi8oSH7qp7pRMv756o',
    appId: '1:418708659686:ios:9eba0e2322372c7dc88a27',
    messagingSenderId: '418708659686',
    projectId: 'linquachat',
    storageBucket: 'linquachat.firebasestorage.app',
    iosBundleId: 'com.example.linguaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ2GLveL72qrI9MAi8oSH7qp7pRMv756o',
    appId: '1:418708659686:ios:9eba0e2322372c7dc88a27',
    messagingSenderId: '418708659686',
    projectId: 'linquachat',
    storageBucket: 'linquachat.firebasestorage.app',
    iosBundleId: 'com.example.linguaChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnd3W2yUHsH2FxqTGCY_afUGNU3oyTlpw',
    appId: '1:418708659686:web:b2f443720f34063ac88a27',
    messagingSenderId: '418708659686',
    projectId: 'linquachat',
    authDomain: 'linquachat.firebaseapp.com',
    storageBucket: 'linquachat.firebasestorage.app',
  );
}
